### ISSUE TITLE
[ISSUE] `apierr.GetAPIError` does not unmarshal `ErrorCode` correctly

### ISSUE THREAD

**Issue by nkvuong** [databricks/databricks-sdk-go#999]
**Description**
`apierr.GetAPIError` does not unmarshal `ErrorCode` correctly

**Reproduction**
Below is a simplified version of `parseErrorFromResponse`
```go
func main() {

	myError := apierr.APIError{
		ErrorCode: "RESOURCE_DOES_NOT_EXIST",
		Message:   "Path (/Users/abc) doesn't exist.",
	}
	b, err := json.Marshal(myError)
	if err != nil {
		panic(err)
	}
	print(b)
	var errorBody struct {
		ErrorCode any    `json:"error_code,omitempty"`
		Message   string `json:"message,omitempty"`
	}
	err = json.Unmarshal(b, &errorBody)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v\n", errorBody)
}
```

**Expected behavior**
errorBody should be populated with ErrorCode & Message, however, ErrorCode is nil in this case
```
{ErrorCode:<nil> Message:Path (/Users/abc) doesn't exist.}
```

**Comment by renaudhartert-db** [comment]
Hi @nkvuong, 

> apierr.GetAPIError does not unmarshal ErrorCode correctly

Do you have an example of an input/ouput pair for `apierr.GetAPIError` that produces the incorrect behavior you are referring to?

**Comment by nkvuong** [comment]
it happened in the failed test in this PR from TF provider - https://github.com/databricks/terraform-provider-databricks/pull/3832. The PR simply replaces the deprecated struct in TF with the Go SDK equivalent.

For example `TestResourceUserDelete_NonExistingDir` should produce no error thanks to the error handling in this line
https://github.com/databricks/terraform-provider-databricks/blob/main/scim/resource_user.go#L156. However, `apierr.IsMissing` is returning false, because the ErrorCode was not unmarshaled correctly.

**Comment by renaudhartert-db** [comment]
I see, thanks! 

I think the core of the problem you're facing is that `apierr.APIError` is not meant to be a substitute for `common.APIErrorBody`. Rather, it is the "higher level" object that are returned by the SDK service clients, not the SDK HTTP client. Making a clear distinction between these two objects is the reason why [the parsing struct was made anonymous](https://github.com/databricks/databricks-sdk-go/blob/main/apierr/errors.go#L167-L178) in `parseErrorFromResponse`. 

It seems that [`resource_user.go`](https://github.com/databricks/terraform-provider-databricks/blob/main/scim/resource_user.go#L156.) is not using the SDK service client but the HTTP client directly. Unfortunately, we cannot use `apierr.IsMissing` on the returned error given that the HTTP client is not returning an `api.APIError` to begin with. 

I think there's two ways we can resolve this:

a. Change the terraform code to use the service client instead of the HTTP client — and then truly deprecate `common.APIErrorBody`. 
b. Implement your own `IsMissing` function that would take a `common.APIErrorBody` struct as parameter.

What do you think?

**Comment by renaudhartert-db** [comment]
Closing this issue as "work as expected"

**Comment by renaudhartert-db** [comment]
Closing this issue as "work as expected"
